In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
Independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
Independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [7]:
Dependent=dataset[['classification_yes']]
Dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators':[1,10,50,100,500],'criterion':['gini','entropy','log_loss'],'max_features':['sqrt','log2']}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Users\nandh\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [1, 10, 50, 100, 500]},
             scoring='f1_weighted', verbose=3)

In [11]:
y_pred=grid.predict(x_test) #(.predict->defined function)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[44  1]
 [ 1 74]]

In [12]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        45
           1       0.99      0.99      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test) 
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print("f1_macro value for {}:".format(grid.best_params_),f1_macro)
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
table=pd.DataFrame.from_dict(re)
table

f1_macro value for {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 500}: 0.9833333333333333

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011132,0.001486,0.007986,0.000927,gini,sqrt,1,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.964572,0.876368,0.909115,0.872761,0.963247,0.917213,0.040179,30
1,0.026681,0.001695,0.008216,0.001082,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.964572,0.947015,0.982051,1.000000,0.978728,0.020602,3
2,0.082558,0.005366,0.007414,0.000808,gini,sqrt,50,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.982051,0.947015,0.982051,0.981728,0.978569,0.017258,8
3,0.152887,0.007317,0.010199,0.001097,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,5
4,0.707092,0.017505,0.022097,0.000643,gini,sqrt,500,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.945469,0.947015,0.982051,0.981728,0.971253,0.021471,22
5,0.006702,0.001668,0.007426,0.001621,gini,log2,1,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.982051,0.875548,0.946153,0.981728,0.953540,0.041394,25
6,0.019742,0.001181,0.006623,0.001279,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,19
7,0.075156,0.001738,0.008539,0.000893,gini,log2,50,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.964286,0.947015,0.982051,1.000000,0.978670,0.020641,4
8,0.151202,0.006093,0.009494,0.001066,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,5
9,0.696201,0.011556,0.022207,0.000767,gini,log2,500,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.963889,0.947015,0.982051,0.981728,0.974937,0.018037,16
10,0.007111,0.002138,0.006016,0.001001,entropy,sqrt,1,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.929144,0.893717,0.929513,0.927778,0.963636,0.928758,0.022118,28
11,0.019634,0.001627,0.005514,0.000835,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.946153,0.912029,0.964286,1.000000,0.964494,0.033497,23
12,0.075930,0.004428,0.007718,0.000400,entropy,sqrt,50,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.963889,0.929513,0.982051,1.000000,0.975090,0.026428,12
13,0.151921,0.005402,0.011867,0.001815,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,9
14,0.723084,0.015974,0.023876,0.003376,entropy,sqrt,500,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,13
15,0.005477,0.000309,0.005908,0.000860,entropy,log2,1,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.928571,0.929513,0.946153,0.907515,0.938795,0.024936,27
16,0.019673,0.002593,0.006012,0.000637,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.964286,0.929513,0.982051,1.000000,0.975170,0.026395,11
17,0.077302,0.002763,0.007719,0.001217,entropy,log2,50,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.964286,0.929513,0.964286,1.000000,0.971617,0.026425,21
18,0.150991,0.006153,0.010016,0.001846,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,19
19,0.707034,0.025680,0.022188,0.000948,entropy,log2,500,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,1
20,0.005926,0.001254,0.006928,0.001025,log_loss,sqrt,1,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.982051,0.910254,0.964572,0.929144,0.925465,0.942297,0.026682,26
21,0.019163,0.002465,0.006961,0.002137,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.964286,0.946153,0.964572,0.946663,0.981894,0.960714,0.013309,24
22,0.081917,0.004640,0.007689,0.001047,log_loss,sqrt,50,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,13
23,0.151079,0.005708,0.009610,0.001202,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,5
24,0.684898,0.012279,0.020619,0.004142,log_loss,sqrt,500,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,17
25,0.006809,0.000684,0.006911,0.000372,log_loss,log2,1,"{'criterion': 'log_loss', 'max_features': 'log...",0.947015,0.836407,0.894531,0.946153,0.963247,0.917470,0.046666,29
26,0.020536,0.001184,0.006864,0.001007,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,1
27,0.077120,0.003122,0.007210,0.000926,log_loss,log2,50,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,17
28,0.148676,0.003555,0.009411,0.000914,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,9
29,0.553771,0.021471,0.012426,0.000394,log_loss,log2,500,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,13