In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
Independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc','sod','pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
Independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [7]:
Dependent=dataset[['classification_yes']]
Dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid={'alpha':[1,5,10,100],'force_alpha':[True,False],'fit_prior':[True,False]}
grid=GridSearchCV(CategoricalNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(Independent,Dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\nandh\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(
C:\Users\nandh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [1, 5, 10, 100], 'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1_weighted', verbose=3)

In [10]:
y_pred=grid.predict(Independent) #(.predict->defined function)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Dependent,y_pred)
print(cm)

[[150   0]
 [  1 248]]

In [11]:
from sklearn.metrics import classification_report
clf_report=classification_report(Dependent,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399

In [12]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test) 
from sklearn.metrics import f1_score
f1_macro=f1_score(Dependent,y_pred,average='weighted')
print("f1_macro value for {}:".format(grid.best_params_),f1_macro)
from sklearn.metrics import roc_auc_score
roc_auc_score(Dependent,grid.predict_proba(Independent)[:,1])
table=pd.DataFrame.from_dict(re)
table

f1_macro value for {'alpha': 1, 'fit_prior': True, 'force_alpha': True}: 0.9974953761738116

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_fit_prior,param_force_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015090,0.002303,0.012668,0.001979,1,True,True,"{'alpha': 1, 'fit_prior': True, 'force_alpha':...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
1,0.017928,0.003625,0.009451,0.001999,1,True,False,"{'alpha': 1, 'fit_prior': True, 'force_alpha':...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
2,0.015338,0.001711,0.009028,0.004445,1,False,True,"{'alpha': 1, 'fit_prior': False, 'force_alpha'...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
3,0.013941,0.003192,0.008233,0.003996,1,False,False,"{'alpha': 1, 'fit_prior': False, 'force_alpha'...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
4,0.012941,0.002311,0.007733,0.001560,5,True,True,"{'alpha': 5, 'fit_prior': True, 'force_alpha':...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
5,0.014537,0.003226,0.005411,0.001722,5,True,False,"{'alpha': 5, 'fit_prior': True, 'force_alpha':...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
6,0.011443,0.001356,0.007275,0.002202,5,False,True,"{'alpha': 5, 'fit_prior': False, 'force_alpha'...",0.938022,NaN,NaN,NaN,NaN,NaN,NaN,1
7,0.012993,0.001265,0.005113,0.002336,5,False,False,"{'alpha': 5, 'fit_prior': False, 'force_alpha'...",0.938022,NaN,NaN,NaN,NaN,NaN,NaN,1
8,0.012491,0.001569,0.006610,0.002461,10,True,True,"{'alpha': 10, 'fit_prior': True, 'force_alpha'...",0.938022,NaN,NaN,NaN,NaN,NaN,NaN,1
9,0.011967,0.001226,0.004458,0.001896,10,True,False,"{'alpha': 10, 'fit_prior': True, 'force_alpha'...",0.938022,NaN,NaN,NaN,NaN,NaN,NaN,1
10,0.011093,0.001210,0.004802,0.001924,10,False,True,"{'alpha': 10, 'fit_prior': False, 'force_alpha...",0.938022,NaN,NaN,NaN,NaN,NaN,NaN,1
11,0.009908,0.000481,0.004512,0.002478,10,False,False,"{'alpha': 10, 'fit_prior': False, 'force_alpha...",0.938022,NaN,NaN,NaN,NaN,NaN,NaN,1
12,0.009940,0.001222,0.006248,0.002959,100,True,True,"{'alpha': 100, 'fit_prior': True, 'force_alpha...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
13,0.010215,0.001240,0.005823,0.001324,100,True,False,"{'alpha': 100, 'fit_prior': True, 'force_alpha...",0.950296,NaN,NaN,NaN,NaN,NaN,NaN,1
14,0.010138,0.001745,0.003560,0.001987,100,False,True,"{'alpha': 100, 'fit_prior': False, 'force_alph...",0.876918,NaN,NaN,NaN,NaN,NaN,NaN,1
15,0.008110,0.001164,0.002622,0.000465,100,False,False,"{'alpha': 100, 'fit_prior': False, 'force_alph...",0.876918,NaN,NaN,NaN,NaN,NaN,NaN,1

In [28]:
import pickle
filename = "Finalized_model_GridSearch_CategoricanNB_Classification.sav"
pickle.dump(grid,open(filename,'wb'))

In [30]:
load_model = pickle.load(open("Finalized_model_GridSearch_CategoricanNB_Classification.sav",'rb'))
result=load_model.predict([[52, 80, 2, 3, 98, 55, 3.1,137,3, 15, 43,
       7200, 5.2, 0,0, 0,1, 1, 1,
       1, 1, 1, 1, 0,
       1, 0, 0]])
result

C:\Users\nandh\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

array([1])